install.packages("rjson")
install.packages("twitteR")
install.packages("ROAuth")
install.packages("jsonlite")
library("twitteR")
library("ROAuth")
library("rjson")
library("jsonlite")
j11data <- fromJSON(sprintf("[%s]", paste(readLines("C:\\Users\\Narmadha\\Desktop\\apt1.json"), collapse=" , ")))
View(j11data)
